#!/usr/bin/env bash

# Show that get_timestamp only returns valid timestamps.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

# It should return a date in the correct format.
assert_success is_timestamp "$(get_timestamp)"

# It should pass its argument on to `date`.
assert_success is_timestamp "$(get_timestamp --date="today - 1 year")"
