#!/usr/bin/env bash

# Show that is_timestamp recognizes the correct timestamp format.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

assert_success is_timestamp "2000-01-01T00:00:00Z"

# This is a valid UTC date, but it's not in the correct format.
assert_failure is_timestamp "2000-01-01T00:00:00+00:00"

# Only recognize ISO-8601 formatted dates.
assert_failure is_timestamp "$(date -d "2000-01-01T00:00:00Z")"

# This one is properly formatted, but not a real date.
assert_failure is_timestamp "0000-00-00T00:00:00Z"

# This one is obviously invalid.
assert_failure is_timestamp "bogus"

# This one is recognized by `date`, but it's still invalid.
assert_failure is_timestamp "now"
