#!/usr/bin/env bash

# Show that timestamp_compare can determine timestamp ordering.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

# There's only one second of difference.
timestamp1=2001-01-01T00:00:01Z
timestamp2=2001-01-01T00:00:02Z

# A "less than" result should return -1.
assert_equal "$(timestamp_compare "$timestamp1" "$timestamp2")" -1

# A "greater than" result should return 1
assert_equal "$(timestamp_compare "$timestamp2" "$timestamp1")" 1

# An "equal to" result should return 0
assert_equal "$(timestamp_compare "$timestamp1" "$timestamp1")" 0
