#!/usr/bin/env bash

# Show that `timestamp_lte` only returns success when the first timestamp occurs
# earlier than or at the same time as the second timestamp.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_no_output assert_success \
    timestamp_lte "$TIMESTAMP" "$TIMESTAMP"

earlier=$(timestamp --date="$TIMESTAMP - 1 second")

assert_no_output assert_success \
    timestamp_lte "$earlier" "$TIMESTAMP"

assert_no_output assert_failure \
    timestamp_lte "$TIMESTAMP" "$earlier"
