#!/usr/bin/env bash

# Show that `timestamp_gte` only returns success when the first timestamp occurs
# later than or at the same time as the second timestamp.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_no_output assert_success \
    timestamp_gte "$TIMESTAMP" "$TIMESTAMP"

later=$(timestamp --date="$TIMESTAMP + 1 second")

assert_no_output assert_success \
    timestamp_gte "$later" "$TIMESTAMP"

assert_no_output assert_failure \
    timestamp_gte "$TIMESTAMP" "$later"
