#!/usr/bin/env bash

# Show that `timestamp_le` only returns success when the first timestamp occurs
# earlier than or at the same time as the second timestamp.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

assert_success assert_no_output \
    timestamp_le "$TIMESTAMP" "$TIMESTAMP"

earlier=$(timestamp --date="$TIMESTAMP - 1 second")

assert_success assert_no_output \
    timestamp_le "$earlier" "$TIMESTAMP"

assert_failure assert_no_output \
    timestamp_le "$TIMESTAMP" "$earlier"
