#!/usr/bin/env bash

# Show that `timestamp_ne` only returns success when timestamps are not equal.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_no_output assert_failure \
    timestamp_ne "$TIMESTAMP" "$TIMESTAMP"

other_timestamp=$(timestamp --date="$TIMESTAMP + 1 second")

assert_success assert_no_output \
    timestamp_ne "$TIMESTAMP" "$other_timestamp"

assert_success assert_no_output \
    timestamp_ne "$other_timestamp" "$TIMESTAMP"
