#!/usr/bin/env bash

# Show that timestamp_compare can determine timestamp ordering.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

# There's only one second of difference.
later=$(get_timestamp --date="$TIMESTAMP + 1 second")

# A "less than" result should return -1.
assert_equal "$(timestamp_compare "$TIMESTAMP" "$later")" -1

# A "greater than" result should return 1
assert_equal "$(timestamp_compare "$later" "$TIMESTAMP")" 1

# An "equal to" result should return 0
assert_equal "$(timestamp_compare "$TIMESTAMP" "$TIMESTAMP")" 0
