#!/usr/bin/env bash

# Show that `timestamp_gt` only returns success when the first timestamp occurs
# later than the second timestamp.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

assert_failure assert_no_output \
    timestamp_gt "$TIMESTAMP" "$TIMESTAMP"

later=$(timestamp --date="$TIMESTAMP + 1 second")

assert_success assert_no_output \
    timestamp_gt "$later" "$TIMESTAMP"

assert_failure assert_no_output \
    timestamp_gt "$TIMESTAMP" "$later"
