#!/usr/bin/env bash

# Show that `timestamp` only returns valid timestamps.

set -euo pipefail

source ./tests/lib/init.bash

# It should return a date in the correct format.
assert_success is_timestamp "$(timestamp)"

# It should pass its argument on to `date`.
assert_success is_timestamp "$(timestamp --date="today - 1 year")"
