#!/usr/bin/env bash

# Show that non-existent profile files cause an error.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export PROFILE_NAME=foo
export PROFILE_FILE=/path/to/$PROFILE_NAME.conf

printf -v stderr \
    "$TEXT_PROFILE_MISSING\n" \
    "$PROFILE_NAME"

assert_failure assert_stderr "$stderr" \
    load_profile
