#!/usr/bin/env bash

# Show that the default snapshot directory can be set.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=foo
defaults_file=$ETC_DIR/defaults.conf

export PROFILE_FILE=$ETC_DIR/$profile_name.conf

mkdir -p "$ETC_DIR"

echo "SUBVOLUME=$TEMP_DIR" >"$PROFILE_FILE"
echo "SNAPSHOTS=$TEMP_DIR" >"$defaults_file"

printf -v stderr "%s\n" \
    "$(format "ERROR: $TEXT_DEFAULTS_SNAPSHOTS_MISSING_NAME")"

assert_failure assert_stderr "$stderr" \
    load_profile

echo "SNAPSHOTS=$TEMP_DIR/%NAME%" >"$defaults_file"

assert_success assert_no_output \
    load_profile

assert_equal "$SNAPSHOTS" "$TEMP_DIR/$profile_name"
