#!/usr/bin/env bash

# Show that the subvolume cannot be set in the defaults configuration.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=foo
profile_dir=$ETC_DIR/profile.d

export PROFILE_FILE=$profile_dir/$profile_name.conf

mkdir -p "$profile_dir"

# Create a profile that does not have the subvolume set.
printf "%s=%s\n" SNAPSHOTS "$TEMP_DIR" >"$PROFILE_FILE"

# If there's no protection, this value will get used.
printf "%s=%s\n" SUBVOLUME "$TEMP_DIR" >"$ETC_DIR"/defaults.conf

printf -v stderr "ERROR: $TEXT_PROFILE_VARIABLE_NOT_SET\n" \
    "$profile_name" SUBVOLUME

assert_failure assert_stderr "$stderr" \
    load_profile
