#!/usr/bin/env bash

# Show that non-existent profile files cause an error.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

printf -v message "%s\n" \
    "ERROR: $(format "$TEXT_PROFILE_NOT_EXIST" PROFILE_NAME=foo)"

export PROFILE_FILE=/path/to/foo.conf

assert_failure assert_stderr "$message" load_profile
