#!/usr/bin/env bash

# Show that the default limit value is zero.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

export PROFILE_FILE=$TEMP_DIR/foo.conf

printf "%s=%s\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$PROFILE_FILE"

assert_no_output assert_success \
    load_profile

# Ensure the base default is zero.
for event_name in "${EVENT_NAMES[@]}"; do
    variable_name=$(get_limit_variable "$event_name")
    assert_equal "${!variable_name}" 0
done
