#!/usr/bin/env bash

# Show that a multiple profiles cannot use the same snapshot location.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_names=(foo bar baz)

for i in "${!profile_names[@]}"; do
    export PROFILE_NAME=${profile_names[i]}
    export PROFILE_FILE=$TEMP_DIR/$PROFILE_NAME.conf

    printf "%s=%s\n" \
        SUBVOLUME "$TEMP_DIR" \
        SNAPSHOTS "$TEMP_DIR" \
        >"$PROFILE_FILE"

    if ((i == 0)); then
        # The snapshot locations are first come, first serve.
        assert_success assert_no_output \
            load_profile
    else
        printf -v stderr \
            "$TEXT_PROFILE_SNAPSHOTS_NOT_UNIQUE\n" \
            "$PROFILE_NAME"

        assert_failure assert_stderr "$stderr" \
            load_profile
    fi
done
