#!/usr/bin/env bash

# Show that errors while loading the defaults file will be reported.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export PROFILE_NAME=foo
export PROFILE_FILE=$CONFIG_DIR/$PROFILE_NAME.conf

defaults_file=$CONFIG_DIR/defaults.conf

mkdir -p "$CONFIG_DIR"

printf "%s=%s\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$PROFILE_FILE"

printf "%s\n" "return 1" >"$defaults_file"

printf -v stderr \
    "$TEXT_SOURCE_FAILED\n" \
    "$defaults_file"

assert_failure assert_stderr "$stderr" \
    load_profile
