#!/usr/bin/env bash

# Show that any available defaults are recognized when loading a profile.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_file=$TEMP_DIR/profile.conf

# Enusre a default snapshot directory will be used.

export DEFAULT_SNAPSHOTS=$TEMP_DIR/snapshots/%NAME%

create_profile_unsafe "$TEMP_DIR" >"$profile_file"

assert_success load_profile "$profile_file"
assert_set SNAPSHOTS
assert_equal "$SNAPSHOTS" "$TEMP_DIR/snapshots/profile"

# Ensure limit variables default to zero.

create_profile "$TEMP_DIR" "$TEMP_DIR" >"$profile_file"
assert_success load_profile "$profile_file"

for event_name in "${EVENT_NAMES[@]}"; do
    limit_variable=$(get_limit_variable "$event_name")
    assert_set "$limit_variable"
    assert_equal "${!limit_variable}" 0
done

# Ensure default values are used if set.

for event_name in "${EVENT_NAMES[@]}"; do
    default_limit_variable=$(get_default_limit_variable "$event_name")
    export "$default_limit_variable=1"
done

assert_success load_profile "$profile_file"

for event_name in "${EVENT_NAMES[@]}"; do
    limit_variable=$(get_limit_variable "$event_name")
    default_limit_variable=$(get_default_limit_variable "$event_name")
    assert_equal "${!limit_variable}" "${!default_limit_variable}"
done
