#!/usr/bin/env bash

# Show that errors while loading the defaults file will be reported.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export PROFILE_FILE=$ETC_DIR/foo.conf

defaults_file=$ETC_DIR/defaults.conf

mkdir -p "$ETC_DIR"

cat >"$PROFILE_FILE" <<-EOF
SUBVOLUME=$TEMP_DIR
SNAPSHOTS=$TEMP_DIR
EOF

echo "return 1" >"$defaults_file"

printf -v stderr "%s\n" \
    "$(format "ERROR: $TEXT_DEFAULTS_LOAD_FAILED" DEFAULTS_FILE="$defaults_file")"

assert_failure assert_stderr "$stderr" \
    load_profile
