#!/usr/bin/env bash

# Show that a profile does not inherit settings from a previously loaded one.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

export PROFILE_FILE=$TEMP_DIR/foo.conf

touch "$PROFILE_FILE"

# Ensure non-inheritance of path variables.
for variable in SUBVOLUME SNAPSHOTS; do
    # Try to trick the function into accepting a non-inheritable value.
    export "$variable=$TEMP_DIR"

    printf -v stderr \
        "$TEXT_PROFILE_VARIABLE_NOT_SET\n" \
        "$PROFILE_FILE" "$variable"

    assert_stderr "$stderr" assert_failure \
        load_profile

    # Skip over this error for the next test.
    printf "%s=%s\n" \
        "$variable" "$TEMP_DIR" \
        >>"$PROFILE_FILE"
done

# Try to trick the function into accepting inheritable values.
for event_name in "${EVENT_NAMES[@]}"; do
    set_limit "$event_name" 1
done

# At this point, the profile is valid, but there are no limits set.
assert_no_output assert_success \
    load_profile

# Ensure non-inheritance of limit values.
for event_name in "${EVENT_NAMES[@]}"; do
    assert_equal "$(get_limit "$event_name")" 0
done
