#!/usr/bin/env bash

# Show that the subvolume cannot be set in the defaults configuration.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_dir=$CONFIG_DIR/profile.d

export PROFILE_FILE=$profile_dir/foo.conf

mkdir -p "$profile_dir"

# Create a profile that does not have the subvolume set.
printf "%s=%s\n" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$PROFILE_FILE"

# If there's no protection, this value will get used.
printf "%s=%s\n" \
    SUBVOLUME "$TEMP_DIR" \
    >"$CONFIG_DIR"/defaults.conf

printf -v stderr \
    "$TEXT_PROFILE_VARIABLE_NOT_SET\n" \
    "$PROFILE_FILE" SUBVOLUME

assert_stderr "$stderr" assert_failure \
    load_profile
