#!/usr/bin/env bash

# Show that errors while loading the defaults file will be reported.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_dir=$ETC_DIR/profile.d
defaults_file=$ETC_DIR/defaults.conf

export PROFILE_FILE=$profile_dir/foo.conf

mkdir -p "$profile_dir"

cat >"$PROFILE_FILE" <<-EOF
SUBVOLUME=$TEMP_DIR
SNAPSHOTS=$TEMP_DIR
EOF

echo "return 1" >"$defaults_file"

printf -v stderr "%s\n" \
    "$(format "ERROR: $TEXT_DEFAULTS_FAILED" DEFAULTS_FILE="$defaults_file")"

assert_failure assert_stderr "$stderr" \
    load_profile
