#!/usr/bin/env bash

# Show that a profile can be loaded under normal circumstances.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

export PROFILE_FILE=$TEMP_DIR/foo.conf

subvolume_dir=$TEMP_DIR/$RANDOM
snapshots_dir=$TEMP_DIR/$RANDOM
limits=()

printf "%s=%s\n" \
    SUBVOLUME "$subvolume_dir" \
    SNAPSHOTS "$snapshots_dir" \
    >"$PROFILE_FILE"

for event_name in "${EVENT_NAMES[@]}"; do
    limit=$((1 + RANDOM))
    limits+=("$limit")

    printf "%s=%d\n" \
        "$(get_limit_variable "$event_name")" "$limit" \
        >>"$PROFILE_FILE"
done

assert_no_output assert_success \
    load_profile

assert_equal "$SUBVOLUME" "$subvolume_dir"
assert_equal "$SNAPSHOTS" "$snapshots_dir"

for i in "${!EVENT_NAMES[@]}"; do
    assert_equal "$(get_limit "${EVENT_NAMES[i]}")" "${limits[i]}"
done
