#!/usr/bin/env bash

# Show that the default snapshot directory can be set.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=foo
defaults_file=$CONFIG_DIR/defaults.conf

export PROFILE_FILE=$CONFIG_DIR/$profile_name.conf

mkdir -p "$CONFIG_DIR"

printf "%s=%s\n" \
    SUBVOLUME "$TEMP_DIR" \
    >"$PROFILE_FILE"

printf "%s=%s\n" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$defaults_file"

printf -v stderr \
    "ERROR: $TEXT_DEFAULTS_SNAPSHOTS_MISSING_PLACEHOLDER\n"

assert_failure assert_stderr "$stderr" \
    load_profile

printf "%s=%s\n" \
    SNAPSHOTS "$TEMP_DIR/%s" \
    >"$defaults_file"

assert_success assert_no_output \
    load_profile

assert_equal "$SNAPSHOTS" "$TEMP_DIR/$profile_name"
