#!/usr/bin/env bash

# Show that `load_profile` will enforce unique `SNAPSHOTS` values.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_names=(a b c)

for i in "${!profile_names[@]}"; do
    export PROFILE_FILE=$TEMP_DIR/${profile_names[i]}.conf

    printf "%s=%s\n" \
        SUBVOLUME "$TEMP_DIR" \
        SNAPSHOTS "$TEMP_DIR" \
        >"$PROFILE_FILE"

    if ((i == 0)); then
        # The snapshot locations are first come, first serve.
        assert_no_output assert_success \
            load_profile
    else
        printf -v stderr \
            "$TEXT_PROFILE_SNAPSHOTS_NOT_UNIQUE\n" \
            "$PROFILE_FILE"

        assert_stderr "$stderr" assert_failure \
            load_profile
    fi
done
