#!/usr/bin/env bash

# Show that default limit values can be set.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

export PROFILE_FILE=$CONFIG_DIR/foo.conf

mkdir -p "$CONFIG_DIR"

printf "%s=%s\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$PROFILE_FILE"

# Create random defaults for every limit.
limits=()
for event_name in "${EVENT_NAMES[@]}"; do
    limit=$((1 + RANDOM))
    limits+=("$limit")

    printf "%s=%d\n" \
        "$(get_limit_variable "$event_name")" "$limit" \
        >>"$CONFIG_DIR"/defaults.conf
done

assert_no_output assert_success \
    load_profile

# Ensure the profile will be using the previously set defaults.
for i in "${!EVENT_NAMES[@]}"; do
    assert_equal "$(get_limit "${EVENT_NAMES[i]}")" "${limits[i]}"
done
