#!/usr/bin/env bash

# Show that no profile selection is the same as selecting all of them when
# creating snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profiles_dir=$ETC_DIR/profiles.d
profile_names=(a b c)
snapshot_paths=()
stdout_lines=()

mkdir -p "$profiles_dir"

for i in "${!profile_names[@]}"; do
    name=${profile_names[i]}
    subvolume=$TEMP_DIR/subvolumes/$name
    snapshots=$TEMP_DIR/snapshots/$name
    snapshot=$snapshots/$TIMESTAMP
    snapshot_paths+=("$snapshot")

    mkdir -p "$subvolume"
    echo -n "$name" >"$subvolume"/marker

    printf "%s\n" \
        SUBVOLUME="$subvolume" \
        SNAPSHOTS="$snapshots" \
        >"$profiles_dir/$name.conf"

    stdout_lines+=("$(
        format "$TEXT_BTRFS_CREATE" \
            SUBVOLUME="$subvolume" \
            SNAPSHOT="$snapshot"
    )")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots create

for i in "${!profile_names[@]}"; do
    marker=${snapshot_paths[i]}/marker
    assert_file "$marker"
    assert_file_content "$marker" "${profile_names[i]}"
done
