#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains about missing option arguments.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_option_needs_arg() {
    stderr="option missing argument: -$1"
    assert_failure assert_stderr_match "$stderr" \
        btrfs-snapshots -"$1"
}

assert_option_needs_arg p
assert_option_needs_arg C
