#!/usr/bin/env bash

# Show that `btrfs-snapshots` displays its version when requested.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

pattern="^[0-9]+\.[0-9]+\.[0-9]+$"

assert_success assert_stdout_match "$pattern" \
    btrfs-snapshots -v

assert_success assert_stdout_match "$pattern" \
    btrfs-snapshots --version
