#!/usr/bin/env bash

# Show that `btrfs-snapshots` creates snapshots for requested profiles.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

profile_names=(a b c)
subvolume_dirs=()
snapshots=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    subvolume_dirs+=("$subvolume_dir")
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots_dir/$TIMESTAMP
    snapshots+=("$snapshot")

    mkdir -p "$subvolume_dir"
    printf "%s" "$profile_name" >"$subvolume_dir"/marker

    printf "%s=%s\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$PROFILES_DIR/$profile_name.conf"
done

selected=(1 2)
options=()
stdout_lines=()

for i in "${selected[@]}"; do
    options+=(--profile="${profile_names[i]}")
    stdout_lines+=("$(printf "$TEXT_BTRFS_CREATE" "${subvolume_dirs[i]}" "${snapshots[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_stdout "$stdout" assert_success \
    btrfs-snapshots "${options[@]}" create

for i in "${selected[@]}"; do
    assert_file "${snapshots[i]}"/marker
    assert_file_content "${snapshots[i]}"/marker "${profile_names[i]}"
done

# Ensure nothing was created for the non-selected profile.
assert_not_exists "${snapshots[0]}"
