#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains when a profile does not exist.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_name=bogus

printf -v stderr \
    "$TEXT_PROFILE_MISSING\n" \
    "$PROFILES_DIR/$profile_name.conf"

for action in create prune list; do
    assert_stderr "$stderr" assert_failure \
        btrfs-snapshots --profile="$profile_name" "$action"
done
