#!/usr/bin/env bash

# Show that `btrfs-snapshots` prunes snapshots for all profiles by default.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

profile_names=(a b c)
snapshots=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots_dir/$TIMESTAMP
    snapshots+=("$snapshot")

    mkdir -p "$snapshot"

    # No limits are set, so every snapshot should be pruned.
    printf "%s=%q\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$PROFILES_DIR/$profile_name.conf"
done

stdout_lines=()

for i in "${!profile_names[@]}"; do
    stdout_lines+=("$(printf "$TEXT_BTRFS_DELETE" "${snapshots[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_stdout "$stdout" assert_success \
    btrfs-snapshots prune

for i in "${!profile_names[@]}"; do
    assert_no_directory "${snapshots[i]}"
done
