#!/usr/bin/env bash

# Show that the profile option requires an argument.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

for option in -p --profile --profile=; do
    printf -v stderr \
        "$TEXT_OPTION_MISSING_ARGUMENT\n" \
        "${option%=}"

    assert_stderr "$stderr" assert_failure \
        btrfs-snapshots "$option"
done
