#!/usr/bin/env bash

# Show that the configuration directory can be overridden.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

alt_config_dir=$TEMP_DIR/alt_config
profile_dir=$alt_config_dir/profile.d

assert_option() {
    subvolume_dir=$TEMP_DIR/subvolume
    snapshots_dir=$TEMP_DIR/snapshots
    snapshot=$snapshots_dir/$TIMESTAMP

    reset_temp

    mkdir -p "$profile_dir" "$subvolume_dir"

    printf "%s=%s\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$profile_dir"/foo.conf

    printf -v stdout \
        "$TEXT_BTRFS_CREATE\n" \
        "$subvolume_dir" "$snapshot"

    assert_success assert_stdout "$stdout" \
        btrfs-snapshots "$@" create

    assert_equal "$(get_snapshots "$snapshots_dir" | wc -l)" 1
}

assert_option -C "$alt_config_dir"
assert_option --config-dir "$alt_config_dir"
assert_option --config-dir="$alt_config_dir"
