#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains when no action is given.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

printf -v stderr "the first argument must be an action\n"

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots ""
