#!/usr/bin/env bash

# Show that multiple profiles can be selected when creating snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profiles_dir=$TEMP_DIR/profiles
timestamp=2001-01-01T00:00:00Z
profile_names=(a b c)
subvolume_paths=()
snapshot_paths=()

mkdir -p "$profiles_dir"

for profile_name in "${profile_names[@]}"; do
    subvolume=$TEMP_DIR/subvolumes/$profile_name
    subvolume_paths+=("$subvolume")
    snapshots=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots/$timestamp
    snapshot_paths+=("$snapshot")

    mkdir -p "$subvolume"
    echo -n "$profile_name" >"$subvolume"/marker

    profile_lines=("SUBVOLUME=$subvolume" "SNAPSHOTS=$snapshots")
    printf "%s\n" "${profile_lines[@]}" >"$profiles_dir/$profile_name.conf"
done

options=()
stdout_lines=()
stderr_lines=()
selected=(1 2)

for i in "${selected[@]}"; do
    options+=(-p "${profile_names[i]}")
    stdout_lines+=("${snapshot_paths[i]}")
    stderr_lines+=("$(format "$TEXT_ACTION" ACTION=create PROFILE_NAME="${profile_names[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"
printf -v stderr "%s\n" "${stderr_lines[@]}"

export BTRFS_SNAPSHOTS_PROFILES_DIR=$profiles_dir
export BTRFS_SNAPSHOTS_TIMESTAMP=$timestamp

assert_success assert_output "$stdout" "$stderr" \
    btrfs-snapshots "${options[@]}" create

for i in "${selected[@]}"; do
    assert_file "${snapshot_paths[i]}"/marker
    assert_file_content "${snapshot_paths[i]}"/marker "${profile_names[i]}"
done
