#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains and takes no action if more than one
# profile uses the same value for `SNAPSHOTS`.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

for profile_name in a b; do
    printf "%s=%q\n" \
        SUBVOLUME "$TEMP_DIR" \
        SNAPSHOTS "$TEMP_DIR" \
        >"$PROFILES_DIR/$profile_name.conf"
done

printf -v stderr \
    "the same value for SNAPSHOTS is used for multiple profiles: %q\n" \
    "$TEMP_DIR"

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots create

assert_equal "$(get_snapshots "$TEMP_DIR" | grep -zc .)" 0
