#!/usr/bin/env bash

# Show that `btrfs-snapshots` displays its version when requested.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

version=$(<"$LIB_DIR"/version)$'\n'

assert_success assert_stdout "$version" \
    btrfs-snapshots -v

assert_success assert_stdout "$version" \
    btrfs-snapshots --version
