#!/usr/bin/env bash

# Show that btrfs errors and exit status are reported.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=foo
profile_dir=$CONFIG_DIR/profile.d
subvolume_dir=$TEMP_DIR/subvolume
snapshots_dir=$TEMP_DIR/snapshots

mkdir -p "$profile_dir" "$subvolume_dir"

# Create a snapshot so there is a reason for calling btrfs during the prune.
mkdir -p "$snapshots_dir/$TIMESTAMP"

printf "%s=%s\n" \
    SUBVOLUME "$subvolume_dir" \
    SNAPSHOTS "$snapshots_dir" \
    >"$profile_dir/$profile_name.conf"

btrfs() {
    return 5
}

export -f btrfs

for action in create prune; do
    stderr_lines=(
        "$(printf "ERROR: $TEXT_BTRFS_FAILED" 5)"
        "$(printf "ERROR: $TEXT_ACTION_FAILED" "$action")"
    )
    printf -v stderr "%s\n" "${stderr_lines[@]}"

    assert_failure assert_stderr "$stderr" \
        btrfs-snapshots -p "$profile_name" "$action"
done
