#!/usr/bin/env bash

# Show that `btrfs-snapshots` processes profiles in a predictable order.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_order() {
    reset_temp

    local stdout_lines=()

    local profile_name
    for profile_name in a b c; do
        local subvolume_dir=$TEMP_DIR/subvolume/$profile_name
        local snapshots_dir=$TEMP_DIR/snapshots/$profile_name
        local snapshot=$snapshots_dir/$TIMESTAMP

        mkdir -p "$PROFILES_DIR" "$subvolume_dir"

        printf "%s=%q\n" \
            SUBVOLUME "$subvolume_dir" \
            SNAPSHOTS "$snapshots_dir" \
            >"$PROFILES_DIR/$profile_name.conf"

        stdout_lines+=("$(printf "$TEXT_BTRFS_CREATE\n" "$subvolume_dir" "$snapshot")")
    done

    local stdout
    printf -v stdout "%s\n" "${stdout_lines[@]}"

    assert_stdout "$stdout" assert_success \
        btrfs-snapshots "$@" create
}

assert_order
assert_order --profile={c,b,a}
