#!/usr/bin/env bash

# Show that an error is reported when the profile does not exist.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=bogus

stderr_lines=(
    "$(printf "$TEXT_PROFILE_MISSING" "$profile_name")"
    "$(printf "$TEXT_PROFILE_LOAD_FAILED" "$profile_name")"
)

printf -v stderr "%s\n" "${stderr_lines[@]}"

for action in create prune; do
    assert_failure assert_stderr "$stderr" \
        btrfs-snapshots -p "$profile_name" "$action"
done
