#!/usr/bin/env bash

# Show that `btrfs-snapshots` displays its version when requested.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

pattern="^[0-9]+\.[0-9]+\.[0-9]+$"

assert_success assert_stdout_match "$pattern" \
    btrfs-snapshots -v

assert_success assert_stdout_match "$pattern" \
    btrfs-snapshots --version
