#!/usr/bin/env bash

# Show that `btrfs-snapshots` recognizes the end-of-options marker.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

option=-h

# If the end-of-options marker is recognized, the next argument will be treated
# as an action, and since $option is not a valid action, it should complain.
printf -v stderr \
    "invalid action: %s\n" \
    "$option"

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots -- "$option"
