#!/usr/bin/env bash

# Show that multiple profiles can be selected when pruning snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profiles_dir=$ETC_DIR/profiles.d
profile_names=(a b c)
snapshot_paths=()

mkdir -p "$profiles_dir"

for profile_name in "${profile_names[@]}"; do
    subvolume=$TEMP_DIR/subvolumes/$profile_name
    snapshots=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots/$TIMESTAMP
    snapshot_paths+=("$snapshot")

    mkdir -p "$snapshot"

    printf "%s\n" \
        SUBVOLUME="$subvolume" \
        SNAPSHOTS="$snapshots" \
        >"$ETC_DIR/profiles.d/$profile_name.conf"
done

options=()
stdout_lines=()
selection=(0 2)

for i in "${selection[@]}"; do
    options+=(-p "${profile_names[i]}")
    stdout_lines+=("$(format "$TEXT_BTRFS_DELETE" SNAPSHOT="${snapshot_paths[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots "${options[@]}" prune

for i in "${selection[@]}"; do
    assert_no_directory "${snapshot_paths[i]}"
done

# Make sure the non-selected profile kept its snapshot.
assert_directory "${snapshot_paths[1]}"
