#!/usr/bin/env bash

# Show that `btrfs-snapshots` lists snapshots for requested profiles.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

profile_names=(a b c)
snapshots=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots_dir/$TIMESTAMP
    snapshots+=("$snapshot")

    mkdir -p "$snapshot"

    printf "%s=%q\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$PROFILES_DIR/$profile_name.conf"
done

selected=(1 2)
selected_profile_names=()
stdout_lines=()

for i in "${selected[@]}"; do
    selected_profile_names+=("${profile_names[i]}")
    stdout_lines+=("${snapshots[i]}")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots list "${selected_profile_names[@]}"
