#!/usr/bin/env bash

# Show that `btrfs-snapshots` displays help when requested.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

for option in -h -? --help; do
    assert_stdout "$TEXT_USAGE"$'\n' assert_success \
        btrfs-snapshots "$option"
done
