#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains and takes no action if any profile
# fails to load.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

# Add a valid profile that would be acted on first under normal circumstances.
# If this profile were processed, there would output to stdout.
printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$PROFILES_DIR"/a.conf

# Add a profile that causes the load to fail.
profile_file=$PROFILES_DIR/b.conf
printf "return 1\n" >"$profile_file"

printf -v stderr "%s\n" \
    "unable to source file: $profile_file" \
    "unable to load profile: $profile_file"

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots create

# Ensure nothing for the valid profile was created.
assert_no_directory "$TEMP_DIR/$TIMESTAMP"
