#!/usr/bin/env bash

# Show that `btrfs-snapshots` recognizes the profile option.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_name=foo
subvolume_dir=$TEMP_DIR/subvolume
snapshots_dir=$TEMP_DIR/snapshots
snapshot=$snapshots_dir/$TIMESTAMP

mkdir -p "$PROFILES_DIR" "$subvolume_dir"

printf "%s=%q\n" \
    SUBVOLUME "$subvolume_dir" \
    SNAPSHOTS "$snapshots_dir" \
    >"$PROFILES_DIR/$profile_name.conf"

printf -v stdout \
    "fake btrfs subvolume snapshot %s %s\n" \
    "$subvolume_dir" "$snapshot"

assert_stdout "$stdout" assert_success \
    btrfs-snapshots -p "$profile_name" create

assert_equal "$(snapshots "$snapshots_dir" | grep -zc .)" 1
