#!/usr/bin/env bash

# Show that the end of options marker is recognized.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

printf -v stderr \
    "$TEXT_ACTION_INVALID\n" \
    -h

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots -- -h
