#!/usr/bin/env bash

# Show that `btrfs-snapshots` lists snapshots for all profiles by default.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_dir=$CONFIG_DIR/profile.d

mkdir -p "$profile_dir"

profile_names=(a b c)
subvolume_dirs=()
snapshots=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    subvolume_dirs+=("$subvolume_dir")
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots_dir/$TIMESTAMP
    snapshots+=("$snapshot")

    mkdir -p "$subvolume_dir"
    printf "%s" "$profile_name" >"$subvolume_dir"/marker

    printf "%s=%s\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$profile_dir/$profile_name.conf"

    mkdir -p "$snapshot"
done

selected=(1 2)
options=()
stdout_lines=()

for i in "${selected[@]}"; do
    options+=(-p "${profile_names[i]}")
    stdout_lines+=("${snapshots[i]}")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_stdout "$stdout" assert_success \
    btrfs-snapshots "${options[@]}" list
