#!/usr/bin/env bash

# Show that `btrfs-snapshots` creates snapshots for all profiles by default.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

profile_names=(a b c)
snapshots=()
stdout_lines=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots_dir/$TIMESTAMP
    snapshots+=("$snapshot")

    mkdir -p "$subvolume_dir"
    printf "%s" "$profile_name" >"$subvolume_dir"/marker

    printf "%s=%q\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$PROFILES_DIR/$profile_name.conf"

    stdout_lines+=("fake btrfs subvolume snapshot $subvolume_dir $snapshot")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots create

for i in "${!profile_names[@]}"; do
    marker=${snapshots[i]}/marker
    assert_file "$marker"
    assert_file_content "$marker" "${profile_names[i]}"
done
