#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains about the configuration directory
# option missing an argument.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

for option in -C --config-dir --config-dir=; do
    printf -v stderr \
        "$TEXT_OPTION_MISSING_ARGUMENT\n" \
        "${option%=}"

    assert_stderr "$stderr" assert_failure \
        btrfs-snapshots "$option"
done
