#!/usr/bin/env bash

# Show that help can be requested at the command line.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

printf -v stderr "%s\n" "$(format "$TEXT_USAGE")"

assert_success assert_stderr "$stderr" \
    btrfs-snapshots -h
