#!/usr/bin/env bash

# Show that requesting the same profile at the command line multiple times will
# only load the profile (and subsequently, perform whatever action) once.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=foo
profile_dir=$ETC_DIR/profile.d
subvolume_dir=$TEMP_DIR/subvolume
snapshots_dir=$TEMP_DIR/snapshots

mkdir -p "$profile_dir"

cat >"$profile_dir/$profile_name.conf" <<-EOF
SUBVOLUME=$subvolume_dir
SNAPSHOTS=$snapshots_dir
EOF

# Notice that there is only one message expected.
printf -v stderr "%s\n" "$(
    format "WARNING: $TEXT_CREATE_SUBVOLUME_MISSING" \
        PROFILE_NAME="$profile_name"
)"

# Notice that the same profile is requested twice.
assert_success assert_stderr "$stderr" \
    btrfs-snapshots -p "$profile_name" -p "$profile_name" create
