#!/usr/bin/env bash

# Show that no profile selection is the same as selecting all of them when
# pruning snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_dir=$ETC_DIR/profile.d

mkdir -p "$profile_dir"

profile_names=(a b c)
snapshots=()

for name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$name
    snapshots_dir=$TEMP_DIR/snapshots/$name
    snapshot=$snapshots_dir/$TIMESTAMP
    snapshots+=("$snapshot")

    mkdir -p "$snapshot"

    printf "%s\n" \
        SUBVOLUME="$subvolume_dir" \
        SNAPSHOTS="$snapshots_dir" \
        >"$profile_dir/$name.conf"
done

stdout_lines=()

for i in "${!profile_names[@]}"; do
    stdout_lines+=("$(format "$TEXT_BTRFS_DELETE" SNAPSHOT="${snapshots[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots prune

for i in "${!profile_names[@]}"; do
    assert_no_directory "${snapshots[i]}"
done
