#!/usr/bin/env bash

# Show that `btrfs-snapshots` deduplicates the selected profiles.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_name=foo
profile_file=$PROFILES_DIR/$profile_name.conf
subvolume_dir=$TEMP_DIR/subvolume
snapshots_dir=$TEMP_DIR/snapshots

mkdir -p "$PROFILES_DIR"

printf "%s=%q\n" \
    SUBVOLUME "$subvolume_dir" \
    SNAPSHOTS "$snapshots_dir" \
    >"$profile_file"

# Notice that there is only one message expected.
printf -v stderr \
    "$TEXT_PROFILE_SUBVOLUME_MISSING\n" \
    "$profile_file" "$subvolume_dir"

# Notice that the same profile is requested twice.
options=(
    --profile="$profile_name"
    --profile="$profile_name"
)

assert_stderr "$stderr" assert_success \
    btrfs-snapshots "${options[@]}" create
