#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains when no action is given.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

action=bogus

printf -v stderr \
    "invalid action: %s\n" \
    "$action"

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots "$action"
