#!/usr/bin/env bash

# Show that multiple profiles can be selected when pruning snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profiles_dir=$TEMP_DIR/profiles
timestamp=2001-01-01T00:00:00Z
profile_names=(a b c)
snapshot_paths=()

mkdir -p "$profiles_dir"

for profile_name in "${profile_names[@]}"; do
    subvolume=$TEMP_DIR/subvolumes/$profile_name
    snapshots=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots/$timestamp
    snapshot_paths+=("$snapshot")

    mkdir -p "$snapshot"

    profile_lines=("SUBVOLUME=$subvolume" "SNAPSHOTS=$snapshots")
    printf "%s\n" "${profile_lines[@]}" >"$profiles_dir/$profile_name.conf"
done

options=()
stdout_lines=()
stderr_lines=()
selection=(0 2)

for i in "${selection[@]}"; do
    options+=(-p "${profile_names[i]}")
    stdout_lines+=("${snapshot_paths[i]}")
    stderr_lines+=("$(format "$TEXT_ACTION" ACTION=prune PROFILE_NAME="${profile_names[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"
printf -v stderr "%s\n" "${stderr_lines[@]}"

export BTRFS_SNAPSHOTS_PROFILES_DIR=$profiles_dir
export BTRFS_SNAPSHOTS_TIMESTAMP=$timestamp

assert_success assert_output "$stdout" "$stderr" \
    btrfs-snapshots "${options[@]}" prune

for i in "${selection[@]}"; do
    assert_no_directory "${snapshot_paths[i]}"
done

# Make sure the non-selected profile kept its snapshot.
assert_directory "${snapshot_paths[1]}"
