#!/usr/bin/env bash

# Show that invalid options are reported.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

option=-x

printf -v stderr "$TEXT_OPTION_INVALID\n" "$option"

assert_failure assert_stderr "$stderr" \
    btrfs-snapshots "$option"
