#!/usr/bin/env bash

# Show that `btrfs-snapshots` prints profile names.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

profile_names=(a b c)
stdout_lines=()

for profile_name in "${profile_names[@]}"; do
    touch "$PROFILES_DIR/$profile_name.conf"
    stdout_lines+=("$profile_name")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots profiles
