#!/usr/bin/env bash

# Show that `btrfs-snapshots` deduplicates the selected profiles.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_name=foo
profile_file=$PROFILES_DIR/$profile_name.conf
subvolume_dir=$TEMP_DIR/subvolume
snapshots_dir=$TEMP_DIR/snapshots

mkdir -p "$PROFILES_DIR"

printf "%s=%q\n" \
    SUBVOLUME "$subvolume_dir" \
    SNAPSHOTS "$snapshots_dir" \
    >"$profile_file"

# Notice that the same profile is requested twice.
readarray -t lines < <(btrfs-snapshots -p "$profile_name" -p "$profile_name" create 2>&1)

# Notice that there is only one message expected.
assert_equal ${#lines[@]} 1
assert_match "${lines[0]}" "subvolume is not available: $subvolume_dir"
