#!/usr/bin/env bash

# Show that the dry-run option is respected when creating snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profiles_dir=$TEMP_DIR/profiles
mkdir -p "$profiles_dir"

profile_name=foo
profile_file=$profiles_dir/$profile_name.conf

timestamp=2001-01-01T00:00:00Z

subvolume=$TEMP_DIR/subvolume
mkdir -p "$subvolume"

snapshots=$TEMP_DIR/snapshots

cat >"$profile_file" <<-EOF
SUBVOLUME=$subvolume
SNAPSHOTS=$snapshots
EOF

snapshot=$snapshots/$timestamp

export BTRFS_SNAPSHOTS_PROFILES_DIR=$profiles_dir
export BTRFS_SNAPSHOTS_TIMESTAMP=$timestamp

printf -v stdout "%s\n" "$snapshot"

printf -v stderr "%s\n" \
    "$(format "$TEXT_ACTION" ACTION=create PROFILE_NAME="$profile_name")"

assert_success assert_output "$stdout" "$stderr" \
    btrfs-snapshots -n create

assert_no_directory "$snapshot"
