#!/usr/bin/env bash

# Show that `btrfs-snapshots` recognizes the end of options marker.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

option=-h

printf -v stderr \
    "$TEXT_ACTION_INVALID\n" \
    "$option"

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots -- "$option"
