#!/usr/bin/env bash

# Show that btrfs errors and exit status are reported.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=foo
profiles_dir=$TEMP_DIR/profiles
subvolume=$TEMP_DIR/subvolume
snapshots=$TEMP_DIR/snapshots
timestamp=2001-01-01T00:00:00Z

mkdir -p "$profiles_dir" "$subvolume" "$snapshots/$timestamp"

cat >"$profiles_dir/$profile_name.conf" <<-EOF
SUBVOLUME=$subvolume
SNAPSHOTS=$snapshots
EOF

btrfs() {
    error "fake message from btrfs"
    return 5
}

export -f btrfs

for action in create prune; do
    printf -v message "%s\n" \
        "$(format "$TEXT_ACTION" ACTION="$action" PROFILE_NAME="$profile_name")" \
        "ERROR: fake message from btrfs" \
        "$(format "ERROR: $TEXT_BTRFS_FAILED" STATUS=5)" \
        "$(format "ERROR: $TEXT_ACTION_FAILED" ACTION="$action")"

    export BTRFS_SNAPSHOTS_PROFILES_DIR=$profiles_dir
    export BTRFS_SNAPSHOTS_TIMESTAMP=$timestamp

    assert_failure assert_stderr "$message" \
        btrfs-snapshots -p foo "$action"
done
