#!/usr/bin/env bash

# Show that `btrfs-snapshots` recognizes multiple profile options.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"

profile_names=(a b c d e)
subvolume_dirs=()
snapshots_dirs=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    subvolume_dirs+=("$subvolume_dir")
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshots_dirs+=("$snapshots_dir")

    mkdir -p "$subvolume_dir"

    printf "%s=%s\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$PROFILES_DIR/$profile_name.conf"
done

stdout_lines=()
options=()

# Pick a selection of profiles and predict the output.
for i in 0 2 4; do
    options+=(--profile="${profile_names[i]}")
    stdout_lines+=("$(printf "$TEXT_BTRFS_CREATE" "${subvolume_dirs[i]}" "${snapshots_dirs[i]}/$TIMESTAMP")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_stdout "$stdout" assert_success \
    btrfs-snapshots "${options[@]}" create
