#!/usr/bin/env bash

# Show that btrfs errors and exit status are reported.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

subvolume=$TEMP_DIR/subvolume
snapshots=$TEMP_DIR/snapshots
profiles_dir=$TEMP_DIR/profiles
profile_name=foo

mkdir -p "$profiles_dir"

cat >"$profiles_dir/$profile_name.conf" <<-EOF
SUBVOLUME=$subvolume
SNAPSHOTS=$snapshots
EOF

export BTRFS_SNAPSHOTS_PROFILES_DIR=$profiles_dir

# Notice that there is only one message expected.
printf -v message "%s\n" \
    "$(format "$TEXT_CREATE_SUBVOLUME_MISSING" PROFILE_NAME="$profile_name")"

# Notice that the same profile is requested twice.
assert_success assert_stderr "$message" \
    btrfs-snapshots -p "$profile_name" -p "$profile_name" create
