#!/usr/bin/env bash

# Show that `btrfs-snapshots` recognizes the configuration directory option.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

config_dir=$TEMP_DIR/alt
profiles_dir=$config_dir/profile.d

assert_option() {
    subvolume_dir=$TEMP_DIR/subvolume
    snapshots_dir=$TEMP_DIR/snapshots
    snapshot=$snapshots_dir/$TIMESTAMP

    reset_temp

    mkdir -p "$profiles_dir" "$subvolume_dir"

    printf "%s=%s\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$profiles_dir"/foo.conf

    printf -v stdout \
        "$TEXT_BTRFS_CREATE\n" \
        "$subvolume_dir" "$snapshot"

    assert_stdout "$stdout" assert_success \
        btrfs-snapshots "$@" create

    assert_equal "$(SNAPSHOTS=$snapshots_dir list | wc -l)" 1
}

assert_option -C "$config_dir"
assert_option --config-dir "$config_dir"
assert_option --config-dir="$config_dir"
