#!/usr/bin/env bash

# Show that an error is reported when the profile does not exist.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=bogus
profile_file=$ETC_DIR/profile.d/$profile_name.conf

printf -v stderr "%s\n" \
    "$(format "ERROR: $TEXT_PROFILE_NOT_EXIST" PROFILE_NAME="$profile_name")" \
    "$(format "ERROR: $TEXT_PROFILE_FAILED" PROFILE_FILE="$profile_file")"

for action in create prune; do
    assert_failure assert_stderr "$stderr" \
        btrfs-snapshots -p "$profile_name" "$action"
done
