#!/usr/bin/env bash

# Show that multiple profiles can be selected when creating snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_dir=$CONFIG_DIR/profile.d

mkdir -p "$profile_dir"

profile_names=(a b c)
subvolume_dirs=()
snapshots=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    subvolume_dirs+=("$subvolume_dir")
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshot=$snapshots_dir/$TIMESTAMP
    snapshots+=("$snapshot")

    mkdir -p "$subvolume_dir"
    printf "%s" "$profile_name" >"$subvolume_dir"/marker

    printf "%s=%s\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$profile_dir/$profile_name.conf"
done

selected=(1 2)
options=()
stdout_lines=()

for i in "${selected[@]}"; do
    options+=(-p "${profile_names[i]}")
    stdout_lines+=("$(printf "$TEXT_BTRFS_CREATE" "${subvolume_dirs[i]}" "${snapshots[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots "${options[@]}" create

for i in "${selected[@]}"; do
    assert_file "${snapshots[i]}"/marker
    assert_file_content "${snapshots[i]}"/marker "${profile_names[i]}"
done
