#!/usr/bin/env bash

# Show that `btrfs-snapshots` displays help when requested.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_success assert_stdout_match ".*Usage:.*Options:.*Arguments:.*Environment:.*" \
    btrfs-snapshots -h
