#!/usr/bin/env bash

# Show that no profile selection is the same as selecting all of them when
# pruning snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profiles_dir=$ETC_DIR/profiles.d
profile_names=(a b c)
snapshot_paths=()

mkdir -p "$profiles_dir"

for name in "${profile_names[@]}"; do
    subvolume=$TEMP_DIR/subvolumes/$name
    snapshots=$TEMP_DIR/snapshots/$name
    snapshot=$snapshots/$TIMESTAMP
    snapshot_paths+=("$snapshot")

    mkdir -p "$snapshot"

    printf "%s\n" \
        SUBVOLUME="$subvolume" \
        SNAPSHOTS="$snapshots" \
        >"$ETC_DIR/profiles.d/$name.conf"
done

stdout_lines=()
for i in "${!profile_names[@]}"; do
    stdout_lines+=("$(format "$TEXT_BTRFS_DELETE" SNAPSHOT="${snapshot_paths[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    btrfs-snapshots prune

for i in "${!profile_names[@]}"; do
    assert_no_directory "${snapshot_paths[i]}"
done
