#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains when no action is given.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

stderr="the first argument must be an action"

assert_failure assert_stderr_match "$stderr" \
    btrfs-snapshots

assert_failure assert_stderr_match "$stderr" \
    btrfs-snapshots ""
