#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains about invalid options.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

printf -v stderr "$TEXT_OPTION_INVALID\n" x

assert_stderr "$stderr" assert_failure \
    btrfs-snapshots -x
