#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains when no action is given.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

action=bogus

stderr="invalid action: $action"

assert_exit_status 2 assert_stderr_match "$stderr" \
    btrfs-snapshots "$action"
