#!/usr/bin/env bash

# Show that `btrfs-snapshots` recognizes multiple profile options.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_names=(a b c d e)

mkdir -p "$PROFILES_DIR"

subvolume_dirs=()
snapshots_dirs=()

for profile_name in "${profile_names[@]}"; do
    subvolume_dir=$TEMP_DIR/subvolume/$profile_name
    subvolume_dirs+=("$subvolume_dir")
    snapshots_dir=$TEMP_DIR/snapshots/$profile_name
    snapshots_dirs+=("$snapshots_dir")

    mkdir -p "$subvolume_dir"

    printf "%s=%s\n" \
        SUBVOLUME "$subvolume_dir" \
        SNAPSHOTS "$snapshots_dir" \
        >"$PROFILES_DIR/$profile_name.conf"
done

selected=(0 2 4)
stdout_lines=()

for i in "${selected[@]}"; do
    stdout_lines+=("$(printf "$TEXT_BTRFS_CREATE" "${subvolume_dirs[i]}" "${snapshots_dirs[i]}/$TIMESTAMP")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_stdout "$stdout" assert_success \
    btrfs-snapshots \
    -p "${profile_names[${selected[0]}]}" \
    --profile "${profile_names[${selected[1]}]}" \
    --profile="${profile_names[${selected[2]}]}" \
    create
