#!/usr/bin/env bash

# Show that no profile selection is the same as selecting all of them when
# creating snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profiles_dir=$TEMP_DIR/profiles.d
timestamp=2001-01-01T00:00:00Z
profile_names=(a b c)
snapshot_paths=()

export BTRFS_SNAPSHOTS_PROFILES_DIR=$profiles_dir
export BTRFS_SNAPSHOTS_TIMESTAMP=$timestamp

mkdir -p "$profiles_dir"

for name in "${profile_names[@]}"; do
    subvolume=$TEMP_DIR/subvolumes/$name
    snapshots=$TEMP_DIR/snapshots/$name
    snapshot=$snapshots/$timestamp
    snapshot_paths+=("$snapshot")

    mkdir -p "$subvolume"
    echo -n "$name" >"$subvolume"/marker

    printf "%s\n" \
        SUBVOLUME="$subvolume" \
        SNAPSHOTS="$snapshots" \
        >"$profiles_dir/$name.conf"
done

stdout_lines=()
stderr_lines=()
for i in "${!profile_names[@]}"; do
    stdout_lines+=("${snapshot_paths[i]}")
    stderr_lines+=("$(format "$TEXT_ACTION" ACTION=create PROFILE_NAME="${profile_names[i]}")")
done

printf -v stdout "%s\n" "${stdout_lines[@]}"
printf -v stderr "%s\n" "${stderr_lines[@]}"

assert_success assert_output "$stdout" "$stderr" \
    btrfs-snapshots create

for i in "${!profile_names[@]}"; do
    marker=${snapshot_paths[i]}/marker
    assert_file "$marker"
    assert_file_content "$marker" "${profile_names[i]}"
done
