#!/usr/bin/env bash

# Show that the dry-run option is respected when pruning snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

profile_name=foo
profiles_dir=$TEMP_DIR/profiles.d
profile_file=$profiles_dir/$profile_name.conf
subvolume=$TEMP_DIR/subvolume
snapshots=$TEMP_DIR/snapshots
timestamp=2001-01-01T00:00:00Z
snapshot=$snapshots/$timestamp

export BTRFS_SNAPSHOTS_PROFILES_DIR=$profiles_dir

mkdir -p "$profiles_dir" "$snapshot"

cat >"$profile_file" <<-EOF
SUBVOLUME=$subvolume
SNAPSHOTS=$snapshots
EOF

printf -v stdout "%s\n" "$snapshot"

printf -v stderr "%s\n" \
    "$(format "$TEXT_ACTION" ACTION=prune PROFILE_NAME="$profile_name")"

assert_success assert_output "$stdout" "$stderr" \
    btrfs-snapshots -n prune

assert_directory "$snapshot"
