#!/usr/bin/env bash

# Show that `load_profile` reports errors when reading defaults.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf

mkdir -p -- "$(dirname -- "$profile_file")"

printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$profile_file"

exit_status=$((RANDOM % 255 + 1))

printf "return %d\n" "$exit_status" >"$DEFAULTS_FILE"

printf -v stderr "test: could not load defaults: %q\n" "$DEFAULTS_FILE"

assert_exit_status "$exit_status" assert_stderr "$stderr" \
    load_profile "$profile_file"
