#!/usr/bin/env bash

# Show that `load_profile` succeeds under normal circumstances.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf
subvolume_dir=$TEMP_DIR/$RANDOM
snapshots_dir=$TEMP_DIR/$RANDOM

mkdir -p "$(dirname "$profile_file")"

printf "%s=%q\n" \
    SUBVOLUME "$subvolume_dir" \
    SNAPSHOTS "$snapshots_dir" \
    >"$profile_file"

limits=()

for event_name in "${EVENT_NAMES[@]}"; do
    limit=$((1 + RANDOM))
    limits+=("$limit")

    printf "%s=%d\n" \
        LIMIT_"${event_name^^}" "$limit" \
        >>"$profile_file"
done

assert_success assert_no_output \
    load_profile "$profile_file"

assert_equal "$SUBVOLUME" "$subvolume_dir"
assert_equal "$SNAPSHOTS" "$snapshots_dir"

for i in "${!EVENT_NAMES[@]}"; do
    variable=LIMIT_${EVENT_NAMES[i]^^}
    assert_equal "${!variable}" "${limits[i]}"
done
