#!/usr/bin/env bash

# Show that `print_profiles` errors with no output when invalid profiles are requested.

set -euo pipefail

source ./lib/init.bash
source ./tests/lib/init.bash

mkdir -p -- "$PROFILES_DIR"
touch -- "$PROFILES_DIR"/{a,b,c}.conf

printf -v stderr "test: profiles do not exist: 'foo' 'bar'\n"

assert_exit_status 78 assert_stderr "$stderr" \
    print_profiles a b foo c bar
