export CONFIG_DIR=$TEMP_DIR/etc
export PROFILES_DIR=$CONFIG_DIR/profile.d
export DEFAULTS_FILE=$CONFIG_DIR/defaults.conf

export TIMESTAMP=2001-01-01T00:00:00Z
export BTRFS_SNAPSHOTS_LIB_DIR=$LIB_DIR
export BTRFS_SNAPSHOTS_CONFIG_DIR=$CONFIG_DIR
export BTRFS_SNAPSHOTS_TIMESTAMP=$TIMESTAMP

. "$ROOT_DIR"/tests/lib/assert.bash
. "$ROOT_DIR"/tests/lib/timestamp.bash
