export TEXT_BTRFS_CREATE="Create a readonly snapshot of '%s' in '%s'"
export TEXT_BTRFS_DELETE="Delete subvolume (no-commit): '%s'"
export TEXT_ASSERT_SET="Variable should have been set: %s"
export TEXT_ASSERT_EQUAL="Values should have been equal: %s != %s"
export TEXT_ASSERT_SUCCESS="Command should have succeeded"
export TEXT_ASSERT_FAILURE="Command should have failed"
export TEXT_ASSERT_OUTPUT="Command output streams should have been equal: %s"
export TEXT_ASSERT_FILE_EXISTS="File should exist: %s"
export TEXT_ASSERT_FILE_NOT_EXISTS="File should not exist: %s"
export TEXT_ASSERT_DIRECTORY_EXISTS="Directory should exist: %s"
export TEXT_ASSERT_DIRECTORY_NOT_EXISTS="Directory should not exist: %s"
export TEXT_ASSERT_PATH_EXISTS="Path should exist: %s"
export TEXT_ASSERT_PATH_NOT_EXISTS="Path should not exist: %s"
export TEXT_ASSERT_FILE_CONTENTS="File contents should have been equal"
export TEXT_ASSERT_ARRAY_LENGTHS_EQUAL="Arrays should be the same length: %d != %d"
export TEXT_ASSERT_ARRAY_ITEMS_EQUAL="Array items at index %d should be equal: %s != %s"
