#!/usr/bin/env bash

# Show that `load_profile` recognizes a default `SNAPSHOTS` setting.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_name=foo
profile_file=$PROFILES_DIR/$profile_name.conf

mkdir -p "$(dirname "$profile_file")"

printf "%s=%s\n" \
    SUBVOLUME "$TEMP_DIR" \
    >"$profile_file"

printf "%s=%s\n" \
    SNAPSHOTS "$TEMP_DIR/%s" \
    >"$DEFAULTS_FILE"

assert_no_output assert_success \
    load_profile "$profile_file"

assert_equal "$SNAPSHOTS" "$TEMP_DIR/$profile_name"
