#!/usr/bin/env bash

# Show that `load_profile` sets all limits to zero, by default.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf

mkdir -p "$(dirname "$profile_file")"

printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$profile_file"

assert_success assert_no_output \
    load_profile "$profile_file"

# Ensure the base default is zero.
for event_name in "${EVENT_NAMES[@]}"; do
    variable=LIMIT_${event_name^^}
    assert_equal "${!variable}" 0
done
