#!/usr/bin/env bash

# Show that `load_profile` ensures `SUBVOLUME` is ignored in the defaults.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf

mkdir -p "$(dirname "$profile_file")"

# Create a profile that does not have the subvolume set.
printf "%s=%q\n" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$profile_file"

# If there's no protection, this value will get used.
printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    >"$DEFAULTS_FILE"

stderr="variable is not set: SUBVOLUME"

assert_failure assert_stderr_match "$stderr" \
    load_profile "$profile_file"
