#!/usr/bin/env bash

# Show that `load_profile` ensures `SUBVOLUME` is ignored in the defaults.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf

mkdir -p "$(dirname "$profile_file")"

# Create a profile that does not have the subvolume set.
printf "%s=%q\n" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$profile_file"

# If there's no protection, this value will get used.
printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    >"$DEFAULTS_FILE"

printf -v stderr \
    "$TEXT_PROFILE_VARIABLE_NOT_SET\n" \
    "$profile_file" SUBVOLUME

assert_stderr "$stderr" assert_failure \
    load_profile "$profile_file"
