#!/usr/bin/env bash

# Show that `load_profile` recognizes default limit values.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf

mkdir -p "$(dirname "$profile_file")"

printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$profile_file"

limits=()

for event_name in "${EVENT_NAMES[@]}"; do
    limit=$((1 + RANDOM))
    limits+=("$limit")

    printf "%s=%d\n" \
        LIMIT_"${event_name^^}" "$limit" \
        >>"$DEFAULTS_FILE"
done

assert_success assert_no_output \
    load_profile "$profile_file"

# Ensure the profile will be using the previously set defaults.
for i in "${!EVENT_NAMES[@]}"; do
    variable=LIMIT_${EVENT_NAMES[i]^^}
    assert_equal "${!variable}" "${limits[i]}"
done
