#!/usr/bin/env bash

# Show that `load_profile` reports errors when reading defaults.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf

mkdir -p "$(dirname "$profile_file")"

printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$profile_file"

printf "return 1\n" >"$DEFAULTS_FILE"

printf -v stderr \
    "unable to source file: %q\n" \
    "$DEFAULTS_FILE"

assert_stderr "$stderr" assert_failure \
    load_profile "$profile_file"
