#!/usr/bin/env bash

# Show that `load_profile` reports errors when reading defaults.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

profile_file=$PROFILES_DIR/foo.conf

mkdir -p "$(dirname "$profile_file")"

printf "%s=%q\n" \
    SUBVOLUME "$TEMP_DIR" \
    SNAPSHOTS "$TEMP_DIR" \
    >"$profile_file"

printf "return 5\n" >"$DEFAULTS_FILE"

stderr="unable to source file: $DEFAULTS_FILE"

assert_exit_status 1 assert_stderr_match "$stderr" \
    load_profile "$profile_file"
