#!/usr/bin/env bash

# Show that `print_profiles` errors with no output when invalid profiles are requested.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

mkdir -p "$PROFILES_DIR"
touch "$PROFILES_DIR"/{a,b,c}.conf

stderr="profiles do not exist: 'foo' 'bar'"

assert_exit_status 2 assert_stderr_match "$stderr" \
    print_profiles a b foo c bar
