#!/usr/bin/env bash

# Show that `btrfs-snapshots prune` complains when a profile does not exist.

set -euo pipefail

source ./tests/lib/init.bash

printf -v stderr "btrfs-snapshots: profiles do not exist: 'foo' 'bar'\n"

assert_failure assert_stderr "$stderr" \
    btrfs-snapshots prune foo bar
