#!/usr/bin/env bash

# Show that `btrfs-snapshots prune` exits with an error if there are no profiles.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

printf -v stderr "btrfs-snapshots: no profiles configured\n"

assert_failure assert_stderr "$stderr" \
    btrfs-snapshots prune
