#!/usr/bin/env bash

# Show that `btrfs-snapshots list` exits with an error if there are no profiles.

set -euo pipefail

source ./lib/init.bash
source ./tests/lib/init.bash

printf -v stderr "btrfs-snapshots: no profiles configured\n"

assert_failure assert_stderr "$stderr" \
    btrfs-snapshots list
