#!/usr/bin/env bash

# Show that `btrfs-snapshots` exits with an error if the profile could not be loaded.

set -euo pipefail

source ./lib/init.bash
source ./tests/lib/init.bash

profile_name=foo
profile_file=$PROFILES_DIR/$profile_name.conf

mkdir -p -- "$PROFILES_DIR"

exit_status=$((RANDOM % 255 + 1))

# Ensure the profile fails to load.
printf "return %d\n" "$exit_status" >"$profile_file"

printf -v stderr "btrfs-snapshots: could not load profile: %q\n" "$profile_file"

assert_exit_status "$exit_status" assert_stderr "$stderr" \
    btrfs-snapshots list "$profile_name"
