#!/usr/bin/env bash

# Show that `btrfs-snapshots` forwards the exit status from btrfs.

set -euo pipefail

source ./tests/lib/init.bash

profile_name=foo
profile_file=$PROFILES_DIR/$profile_name.conf
subvolume_dir=$TEMP_DIR/subvolume
snapshots_dir=$TEMP_DIR/snapshots

mkdir -p -- "$PROFILES_DIR" "$subvolume_dir"

# Create a snapshot so there is a reason for calling btrfs during the prune.
mkdir -p -- "$snapshots_dir/$TIMESTAMP"

# Omit any limit settings, so everything will be pruned.
printf "%s=%q\n" \
    SUBVOLUME "$subvolume_dir" \
    SNAPSHOTS "$snapshots_dir" \
    >"$profile_file"

printf -v stderr "something bad happened\n"

bin_dir=$TEMP_DIR/bin
export PATH=$bin_dir:$PATH

exit_status=$((RANDOM % 255 + 1))

# Fake implementation of `btrfs` that always errors.
mkdir -p "$bin_dir"
cat >"$bin_dir"/btrfs <<EOF
#!/usr/bin/env bash
printf "$stderr" >&2
exit $exit_status
EOF
chmod 755 "$bin_dir"/btrfs

for action in create prune; do
    assert_exit_status "$exit_status" assert_stderr "$stderr" \
        btrfs-snapshots "$action" "$profile_name"
done
