#!/usr/bin/env bash

# Show that `btrfs-snapshots` displays help when requested.

set -euo pipefail

source ./tests/lib/init.bash

pattern=".*Usage:.*Actions:.*Arguments:.*Environment:.*"

assert_success assert_stdout_match "$pattern" \
    btrfs-snapshots -h

assert_success assert_stdout_match "$pattern" \
    btrfs-snapshots --help
