#!/usr/bin/env bash

# Show that `btrfs-snapshots` displays its version when requested.

set -euo pipefail

source ./tests/lib/init.bash

version=$(<./lib/version)$'\n'

assert_success assert_stdout "$version" \
    btrfs-snapshots -v

assert_success assert_stdout "$version" \
    btrfs-snapshots --version
