#!/usr/bin/env bash

# Show that `btrfs-snapshots` complains when no action is given.

set -euo pipefail

source ./tests/lib/init.bash

action=bogus

printf -v stderr "btrfs-snapshots: invalid action: %s\n" "$action"

assert_exit_status 64 assert_stderr "$stderr" \
    btrfs-snapshots "$action"
