#!/usr/bin/env bash

# Show that `is_same_event` can identify timestamps occurring in the same week.

set -euo pipefail

source ./lib/init.bash
source ./tests/lib/init.bash

# Select a random week in an ISO year.
event_start=$(timestamp -d "2000-01-03T00:00:00Z + $((RANDOM % 52)) weeks")
event_stop=$(timestamp -d "$event_start + 1 week - 1 second")

# Ensure a tiny step before the first day of the week is considered a different event.
assert_failure assert_no_output \
    is_same_event weekly "$event_start" "$(timestamp -d "$event_start - 1 second")"

# Ensure a tiny step after the last day of the week is considered a different event.
assert_failure assert_no_output \
    is_same_event weekly "$event_stop" "$(timestamp --date="$event_stop + 1 second")"

# Ensure every day of the week is considered the same event.
while read -r event_step; do
    assert_success assert_no_output \
        is_same_event weekly "$event_start" "$event_step"
done < <(timestamp_seq "$event_start" "1 day" 7)

# Ensure adjacent years with the same week number appear as the same event.
assert_success assert_no_output \
    is_same_event weekly 1999-12-31T00:00:00Z 2000-01-01T23:00:00Z

# Ensure non-adjacent years with the same week number do not appear as the same event.
assert_failure assert_no_output \
    is_same_event weekly 2000-01-03T00:00:00Z 2002-01-01T00:00:00Z
