#!/usr/bin/env bash

# Show that `is_same_event` can recognize timestamps occurring within the same
# monthly event.

set -euo pipefail

source ./tests/lib/init.bash

event_start=2000-$((RANDOM % 12 + 1))-01T00:00:00Z
event_stop=$(timestamp -d "$event_start + 1 month - 1 second")

# Ensure a tiny step before the event window is considered a different event.
assert_failure assert_no_output \
    is_same_event monthly "$event_start" "$(timestamp -d "$event_start - 1 second")"

# Ensure a tiny step after the event window is considered a different event.
assert_failure assert_no_output \
    is_same_event monthly "$event_stop" "$(timestamp -d "$event_stop + 1 second")"

# Ensure every day of the month is in the same event window.
while read -r event_step; do
    assert_success assert_no_output \
        is_same_event monthly "$event_start" "$event_step"
done < <(timestamp_range "$event_start" "$event_stop" "1 day")
