.TH btrfs\-snapshots.conf 5

.SH NAME
btrfs\-snapshots.conf - btrfs-snapshots main configuration file

.SH SYNOPSIS
/usr/local/etc/btrfs-snapshots.conf

.SH DESCRIPTION
Configuration options common to all profiles are stored in this file.

An example file is located in the share directory:
.IP
\fI/usr/local/share/btrfs-snapshots/main.conf\fR.

.SH OPTIONS

.IP \fBDEFAULT_SNAPSHOTS\fR="/path/to/snapshots/%NAME%"
This option defines the default snapshot location for subvolumes that do not
have the option \fBSNAPSHOTS\fR set in their profile. This is useful in cases
where you have a central location for snapshots, but have them subdivided by
name.

It's not required, but if set, %NAME% should appear somewhere in the right-hand
side.  This will be replaced at run time with the profile name.

For example, let's say it's defined as `/.snapshots/%NAME%`. There are three
profiles in \fI/usr/local/etc/btrfs-snapshots.d\fR named `@.conf`, `@home.conf`, and
`@var.conf`. The command to create snapshots is run at 12 noon (UTC) on December
31st 2021.  There will be three snapshots created and stored like so:

.RS 16
.nf
/.snapshots
├── @
│   └── 2021-12-31T12:00:00Z
├── @home
│   └── 2021-12-31T12:00:00Z
└── @var
    └── 2021-12-31T12:00:00Z
.fi
.RE

.IP \fBDEFAULT_LIMIT_<EVENT>\fR=<NUMBER>
This option defines a default limit on the number (specified by NUMBER) of the
first snapshots taken during the EVENT recurrence, where EVENT is one of the
following: MINUTELY, HOURLY, DAILY, WEEKLY, MONTHLY, QUARTERLY, or YEARLY.

There can be zero or more default limits set. For any default limit left
unspecified, the implicit value for NUMBER is zero (0). See
\fBbtrfs\-snapshots.d\fR(5) for details on how limits work.

.SH SEE ALSO
.BR btrfs\-snapshots (8),
.BR btrfs\-snapshots.d (5)
