#!/usr/bin/env bash

# Show that get_limit_variable constructs the correct variable name.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_equal "$(get_limit_variable whatever)" LIMIT_WHATEVER
