#!/usr/bin/env bash

# Show that is_limit_enabled only considers non-zero values to be enabled.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

name=whatever
assert_failure is_limit_enabled "$name"

set_limit "$name" 0
assert_failure is_limit_enabled "$name"

set_limit "$name" 1
assert_success is_limit_enabled "$name"
