#!/usr/bin/env bash

# Show that set_limit correctly stores the limit value.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

assert_equal "$(get_limit whatever)" 0

limit=5
set_limit whatever "$limit"
assert_equal "$(get_limit whatever)" "$limit"
