#!/usr/bin/env bash

# Show that set_limit correctly stores the limit value.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

default=0
assert_equal "$(get_limit whatever)" "$default"

limit=5
set_limit whatever "$limit"
assert_equal "$(get_limit whatever)" "$limit"
