#!/usr/bin/env bash

# Show that `is_timestamp` recognizes the correct timestamp format.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

assert_success is_timestamp "$TIMESTAMP"

# Empty input should be rejected.
assert_failure is_timestamp ""

# Nonsense should be rejected.
assert_failure is_timestamp bogus

# This one is recognized by `date`, but it's still invalid.
assert_failure is_timestamp now

# This is a valid date, but is not ISO-8601 formatted.
assert_failure is_timestamp "$(date)"

# This is a valid ISO-8601 formatted UTC date, but not in "zulu time" form.
assert_failure is_timestamp 2000-01-01T00:00:00+00:00

# This one is properly formatted, but not a real date.
assert_failure is_timestamp 0000-00-00T00:00:00Z
