#!/usr/bin/env bash

# Show that `timestamp_cmp` can determine timestamp ordering.

set -euo pipefail

source "$LIB_DIR"/init.bash
source "$TESTS_LIB_DIR"/init.bash

# There's only one second of difference.
later=$(timestamp --date="$TIMESTAMP + 1 second")

# A "less than" result should return -1.
assert_equal "$(timestamp_cmp "$TIMESTAMP" "$later")" -1

# A "greater than" result should return 1
assert_equal "$(timestamp_cmp "$later" "$TIMESTAMP")" 1

# An "equal to" result should return 0
assert_equal "$(timestamp_cmp "$later" "$later")" 0
assert_equal "$(timestamp_cmp "$TIMESTAMP" "$TIMESTAMP")" 0
