#!/usr/bin/env bash

set -euo pipefail

name=btrfs-snapshots
src_dir=$PWD
dst_dir=${DESTDIR:-}${PREFIX:-/usr/local}

mkdir -p "$dst_dir"
cd "$dst_dir"

install -m755 -Dt ./bin "$src_dir"/bin/*

install -m644 -Dt ./lib/"$name" "$src_dir"/lib/*

for input in "$src_dir"/man/*.scd; do
    base=$(basename "$file" .scd)
    output=$src_dir/man/$base
    scdoc <"$input" >"$output"
    section=${base##*.}
    install -m644 -DT "$output" ./share/man/man"$section"/"$base"
done

install -m644 -Dt ./lib/systemd/system "$src_dir"/systemd/*

install -m644 -Dt ./share/doc/"$name"/config "$src_dir"/config/*

install -m644 -Dt ./share/doc/"$name" "$src_dir"/{README,LICENSE}.md

for file in "$src_dir"/completion/*.zsh; do
    name=$(basename "$file" .zsh)
    install -m644 -DT "$file" ./share/zsh/site-functions/_"$name"
done

for file in "$src_dir"/completion/*.bash; do
    name=$(basename "$file" .bash)
    install -m644 -DT "$file" ./share/bash-completion/completions/"$name"
done
