#!/usr/bin/env bash

set -euo pipefail

PREFIX=${PREFIX:-/usr/local}

if [[ $PREFIX == /usr ]]; then
    etc_dir=/etc
else
    etc_dir=$PREFIX/etc
fi

sed -i "1s:#\!.*/env \(.*\)$:#\!/usr/bin/\1:" ./bin/*

sed -i \
    -e "s:\./bin:$PREFIX/bin:g" \
    -e "s:\./etc:$etc_dir/btrfs-snapshots:g" \
    -e "s:\./lib:$PREFIX/lib/btrfs-snapshots:g" \
    -e "s:\./share/doc:$PREFIX/share/doc/btrfs-snapshots:g" \
    ./bin/* ./lib/* ./man/* ./share/doc/config/* ./systemd/* ./completion/*/*
