#!/usr/bin/env bash

set -euo pipefail

PREFIX=${PREFIX:-/usr/local}

if [[ $PREFIX == /usr ]]; then
    etc_dir=/etc
else
    etc_dir=$PREFIX/etc
fi

sed -i \
    -e "1s:#\!.*/env \(.*\)$:#\!/usr/bin/\1:" \
    ./bin/*

sed -i \
    -e "s:\./bin\b:$PREFIX/bin:g" \
    -e "s:\./etc\b:$etc_dir/btrfs-snapshots:g" \
    -e "s:\./lib\b:$PREFIX/lib/btrfs-snapshots:g" \
    -e "s:\./share/doc\b:$PREFIX/share/doc/btrfs-snapshots:g" \
    ./bin/* ./lib/* ./man/* ./share/doc/config/* ./systemd/* ./completion/*/*
