#!/usr/bin/env bash

set -euo pipefail

root_dir=$PWD

export LIB_DIR=$root_dir/lib
export TESTS_LIB_DIR=$root_dir/tests/lib

PATH=$root_dir/bin:$root_dir/tests/bin:$PATH

self_name=${0##*/}

test_file=${1:?missing test file}

TEMP_DIR=$(mktemp -d -t "$self_name".XXXXXXXXXX)
trap 'rm -rf "$TEMP_DIR"' EXIT

export TEMP_DIR

if ! "$test_file"; then
    printf "test failed: %q\n" "$test_file" >&2
    exit 1
fi
