#!/usr/bin/env bash

set -euo pipefail

export PATH=$PWD/tests/bin:$PWD/bin:$PATH

export LIB_DIR=$PWD/lib
export TESTS_LIB_DIR=$PWD/tests/lib

run_test() {
    local file=$1

    if ((${TESTS_VERBOSE:-0})); then
        printf "Running test: %q\n" "$file"
    fi

    if ! "$file"; then
        printf "Test failed: %q\n" "$file" >&2
        return 1
    fi
}

export -f run_test

find tests/{unit,integration} -type f -executable "$@" -print0 |
    parallel --shuf --jobs=0 --null run_test
