#!/usr/bin/env bash

set -euo pipefail

export LIB_DIR=$PWD/lib
export TESTS_LIB_DIR=$PWD/tests/lib

PATH=$PWD/bin:$PWD/tests/bin:$PATH

self_name=${0##*/}

test_file=${1:?missing test file}

test_id=${test_file##*/}

TEMP_DIR=$(mktemp -d -t "$self_name-$test_id".XXXXXXXXXX)

cleanup() {
    rm -rf "$TEMP_DIR"
}

trap cleanup EXIT

export TEMP_DIR

if ! "$test_file"; then
    printf "test failed: %q\n" "$test_file" >&2
    exit 1
fi
