#!/usr/bin/env bash

set -euo pipefail

version=${1:?missing version}
version=v${version##v}

sed -i "/^version=/s/=.*/=$version/" ./bin/*
git add ./bin/*

git commit -m "Bump version"
git tag "$version"
