#!/usr/bin/env bash

# Show that `is_same_event` can recognize timestamps occurring within the same
# minutely event.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

# Ensure a tiny step before the event window is considered a different event.
assert_failure assert_no_output \
    is_same_event minutely "$TIMESTAMP" "$(timestamp -d "$TIMESTAMP - 1 second")"

# Ensure every second of the minute is in the same event window.
while read -r event_step; do
    assert_success assert_no_output \
        is_same_event minutely "$TIMESTAMP" "$event_step"
done < <(timestamp_seq "$TIMESTAMP" "1 second" 60)

# Ensure a tiny step after the event window is considered a different event.
assert_failure assert_no_output \
    is_same_event minutely "$TIMESTAMP" "$(timestamp -d "$event_step + 1 second")"
