#!/usr/bin/env bash

# Show that if the configuration directory has been overridden, the profile
# completion choices come from there instead.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

alt_etc_dir=$TEMP_DIR/alt_etc
alt_profile_dir=$alt_etc_dir/profile.d
mkdir -p "$alt_profile_dir"
touch "$alt_profile_dir"/{a,b,c}.conf

_init_completion() {
    cur=""
    prev="-p"
    words=("btrfs-snapshots" "-C" "$alt_etc_dir" -p "")
}

export -f _init_completion

. "$PWD/completion/btrfs-snapshots.bash"

_btrfs_snapshots

profiles=(a b c)
assert_arrays_equal COMPREPLY profiles
