#!/usr/bin/env bash

# Show that profile names are completed if there are some.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

_init_completion() {
    # shellcheck disable=SC2034
    cur=""
    # shellcheck disable=SC2034
    prev="-p"
    # shellcheck disable=SC2034
    words=("btrfs-snapshots" "-p" "")
}

export -f _init_completion

. "$PWD/completion/btrfs-snapshots.bash"

profile_dir=$ETC_DIR/profile.d
mkdir -p "$profile_dir"
touch "$profile_dir"/{a,b,c}.conf

_btrfs_snapshots

# shellcheck disable=SC2034
profiles=(a b c)

assert_arrays_equal COMPREPLY profiles
