#!/usr/bin/env bash

# Show that the configuration directory option completes with directories.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

_init_completion() {
    # shellcheck disable=SC2034
    cur=""
    # shellcheck disable=SC2034
    prev="-C"
    # shellcheck disable=SC2034
    words=("btrfs-snapshots" "-C" "")
}

_filedir() {
    assert_equal "$1" -d
    COMPREPLY=(a b c)
}

export -f _init_completion

. "$PWD/completion/btrfs-snapshots.bash"

_btrfs_snapshots

# shellcheck disable=SC2034
directories=(a b c)

assert_arrays_equal COMPREPLY directories
