#!/usr/bin/env bash

# Show that no profiles are completed if there are none.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

_init_completion() {
    # shellcheck disable=SC2034
    cur=""
    # shellcheck disable=SC2034
    prev="-p"
    # shellcheck disable=SC2034
    words=("btrfs-snapshots" "-p" "")
}

export -f _init_completion

. "$PWD/completion/btrfs-snapshots.bash"

# shellcheck disable=SC2034
profiles=()

_btrfs_snapshots

assert_arrays_equal COMPREPLY profiles
