.TH btrfs\-snapshots 8

.SH NAME
btrfs\-snapshots \- Manage collections of btrfs snapshots

.SH SYNOPSIS
.B btrfs\-snapshots
[\fIOPTIONS\fR] \fIACTION\fR

.SH DESCRIPTION
The purpose of \fBbtrfs\-snapshots\fR is to make the process of taking subvolume
snapshots automatic and predictable.

.PP
It makes no assumptions about the subvolume layout.  It does not modify the
system in any way.  It does have two strict requirements, however, which are
debatably painless:

.RS
.nr step 1 1
.IP \n[step] 3
A snapshot's base name is the UTC timestamp when it was taken
.IP \n+[step]
The snapshots for each subvolume must be in their own directory
.RE

.PP
No configuration is done implicitly, and is left entirely up to the
administrator.  This is described in the \fBCONFIGURATION\fR and \fBPROFILES\fR
sections, and their related manuals.
.SH ACTIONS

.IP \fBcreate\fR
.br
Create a new snapshot for each selected profile in the configured directory with
a base name that is the UTC timestamp when it is created (e.g.
2021\-12\-31T12:34:56Z).

.IP \fBprune\fR
.br
Delete all snapshots for each selected profile that fall outside of the
configured limits.

.SH OPTIONS

.TP 10
.B \-h
Display the help message and exit.

.TP
.B \-n
Only report what would happen (no changes are made).

.TP
.B \-p \fINAME\fR
Only perform \fIACTION\fR on the profile \fINAME\fR.
Can be specified multiple times to select multiple profiles.

.SH CONFIGURATION
See \fBbtrfs\-snapshots.conf\fR(5) for more details on configuring the defaults
that btrfs\-snapshots uses.

.SH PROFILES
See \fBbtrfs\-snapshots.d\fR(5) for more details on configuring the subvolumes
that btrfs\-snapshots operates on.

.SH TIMERS
.PP
While not a requirement, the intention is that snapshots will be automatically
created and pruned using the included
.BR systemd.timer (5)
units that correspond to the two actions available at the command line:

.IP \fIbtrfs\-snapshots\-create.timer\fR
.br
This timer creates snapshots for each configured subvolume at a regular interval
(hourly, by default).
.IP \fIbtrfs\-snapshots\-prune.timer\fR
.br
This timer deletes all of the snapshots that fall outside of the configured
limits at a regular interval (daily, by default).

Both timers must be enabled explicitly.


.SH SEE ALSO
.BR btrfs\-snapshots.conf (5),
.BR btrfs\-snapshots.d (5)

.SH REPORTING BUGS
For bug reports, use the issue tracker at
.br
.nf
https://gitlab.com/jmcantrell/btrfs\-snapshots/\-/issues
.fi
