#!/usr/bin/env bash

# Show that create respects the dry-run setting.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export SUBVOLUME=$TEMP_DIR/subvolume
export SNAPSHOTS=$TEMP_DIR/snapshots
export BTRFS_SNAPSHOTS_TIMESTAMP=2001-01-01T00:00:00Z
export PROFILE_NAME=foo
export DRY_RUN=1

snapshot=$SNAPSHOTS/$BTRFS_SNAPSHOTS_TIMESTAMP

mkdir -p "$SUBVOLUME"

printf -v stdout "%s\n" "$snapshot"

printf -v stderr "%s\n" \
    "$(format "$TEXT_ACTION" ACTION=create PROFILE_NAME)"

assert_success assert_output "$stdout" "$stderr" \
    create

assert_no_directory "$snapshot"
