#!/usr/bin/env bash

# Show that `create` succeeds under normal circumstances.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

export SUBVOLUME=$TEMP_DIR/subvolume
export SNAPSHOTS=$TEMP_DIR/snapshots

snapshot=$SNAPSHOTS/$TIMESTAMP

mkdir -p "$SUBVOLUME"
touch "$SUBVOLUME"/marker

printf -v stdout \
    "fake btrfs subvolume snapshot %s %s\n" \
    "$SUBVOLUME" "$snapshot"

assert_success assert_stdout "$stdout" \
    action_create

assert_directory "$snapshot"
assert_file "$snapshot"/marker
