#!/usr/bin/env bash

# Show that create succeeds under normal circumstances.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export SUBVOLUME=$TEMP_DIR/subvolume
export SNAPSHOTS=$TEMP_DIR/snapshots
export PROFILE_NAME=foo

snapshot=$SNAPSHOTS/$TIMESTAMP

mkdir -p "$SUBVOLUME"
touch "$SUBVOLUME"/marker

printf -v stdout "%s\n" \
    "$(format "$TEXT_BTRFS_CREATE" SUBVOLUME SNAPSHOT="$snapshot")"

assert_success assert_stdout "$stdout" \
    create

assert_directory "$snapshot"
assert_file "$snapshot"/marker
