#!/usr/bin/env bash

# Show that create reports a missing subvolume and does nothing.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export SUBVOLUME=$TEMP_DIR/subvolume
export SNAPSHOTS=$TEMP_DIR/snapshots
export PROFILE_NAME=foo

printf -v stderr \
    "$TEXT_PROFILE_SUBVOLUME_MISSING\n" \
    "$PROFILE_NAME" "$SUBVOLUME"

assert_success assert_stderr "$stderr" \
    create

assert_equal "$(list | wc -l)" 0
