#!/usr/bin/env bash

# Show that snapshots will be listed in chronological order.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export SNAPSHOTS=$TEMP_DIR

assert_success assert_no_output \
    list

stdout_lines=()

while IFS= read -r -d $'\n' timestamp_step; do
    snapshot=$TEMP_DIR/$timestamp_step
    stdout_lines+=("$snapshot")
    mkdir -p "$snapshot"
done < <(timestamp_sequence "$TIMESTAMP" "1 hour" 10)

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_success assert_stdout "$stdout" \
    list
