#!/usr/bin/env bash

# Show that `list` outputs snapshots in chronological order.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

export SNAPSHOTS=$TEMP_DIR

assert_no_output assert_success \
    list

stdout_lines=()

while read -r timestamp_step; do
    snapshot=$TEMP_DIR/$timestamp_step
    stdout_lines+=("$snapshot")
    mkdir -p "$snapshot"
done < <(timestamp_seq "$TIMESTAMP" "1 hour" 10)

printf -v stdout "%s\n" "${stdout_lines[@]}"

assert_stdout "$stdout" assert_success \
    list
