#!/usr/bin/env bash

# Show that `profiles` will print all profile names.

set -euo pipefail

. "$LIB_DIR"/init.bash
. "$TESTS_LIB_DIR"/init.bash

# Add some invalid paths (that should not be returned).
mkdir -p "$PROFILES_DIR"/dir            # directory
touch "$PROFILES_DIR"/dir/deep.conf     # nested profile
touch "$PROFILES_DIR"/not_a_profile.txt # incorrect extension

touch "$PROFILES_DIR"/{@,@home,@var}.conf

printf -v stdout "%s\n" @ @home @var

assert_success assert_stdout "$stdout" \
    do_profiles
