#!/usr/bin/env bash

# Show that prune does nothing when there are no snapshots.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

export SNAPSHOTS=$TEMP_DIR/snapshots
export PROFILE_NAME=foo

printf -v stderr "%s\n" \
    "$(format "$TEXT_ACTION" ACTION=prune PROFILE_NAME)"

assert_success assert_stderr "$stderr" \
    prune
