#!/usr/bin/env bash

# Show that prune respects the dry-run setting.

set -eu

. "$LIB_DIR"/init.sh
. "$TESTS_LIB_DIR"/init.sh

subvolume=$TEMP_DIR/subvolume
snapshots=$TEMP_DIR/snapshots
profile_name=foo
timestamp=2001-01-01T00:00:00Z
snapshot=$snapshots/$timestamp

mkdir -p "$snapshot"

printf -v stdout "%s\n" "$snapshot"

printf -v stderr "%s\n" \
    "$(format "$TEXT_ACTION" ACTION=prune PROFILE_NAME="$profile_name")"

export SUBVOLUME=$subvolume
export SNAPSHOTS=$snapshots
export PROFILE_NAME=$profile_name
export DRY_RUN=1

assert_success assert_output "$stdout" "$stderr" \
    prune

assert_directory "$snapshot"
